# Generated by Django 5.2.17 on 2026-08-05 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringBandMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=16)),
                ('raw_score_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('raw_score_max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('band_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_band_mappings', to='test_catalog.test')),
            ],
            options={
                'ordering': ['section_type', 'raw_score_min'],
            },
        ),
    ]
