# Generated by Django 6.0 on 2025-12-22 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('test_number', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='listening_audio/')),
                ('transcript', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('form_completion', 'Form Completion'), ('map_labeling', 'Map Labeling'), ('sentence_completion', 'Sentence Completion')], max_length=30)),
                ('correct_answer', models.TextField()),
                ('field_count', models.IntegerField(default=1)),
                ('time_start', models.IntegerField(default=0)),
                ('time_end', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='listening.listeningsection')),
            ],
        ),
        migrations.AddField(
            model_name='listeningsection',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='listening.listeningtest'),
        ),
        migrations.CreateModel(
            name='UserListeningAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('band_score', models.FloatField(default=0)),
                ('time_taken', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.listeningtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
