# Generated by Django 5.2.17 on 2026-08-05 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('section_type', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=16)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('extra_transfer_time_seconds', models.PositiveIntegerField(default=0)),
                ('instruction_text', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_locked_by_default', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('source_note', models.CharField(blank=True, max_length=512)),
                ('license_note', models.CharField(blank=True, max_length=512)),
                ('is_original_sample', models.BooleanField(default=False)),
                ('is_copyable_default', models.BooleanField(default=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='test_catalog.section')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='audio_assets/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('transcript', models.TextField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('storage_provider', models.CharField(blank=True, max_length=128)),
                ('signed_url_expires_at', models.DateTimeField(blank=True, null=True)),
                ('original_license', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('playback_policy', models.JSONField(blank=True, default=dict)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_assets', to='test_catalog.section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('module_type', models.CharField(choices=[('academic', 'Academic'), ('general', 'General'), ('both', 'Both')], default='both', max_length=16)),
                ('attempt_limit', models.PositiveIntegerField(default=0)),
                ('strict_exam_mode', models.BooleanField(default=False)),
                ('allow_practice_replay', models.BooleanField(default=True)),
                ('copy_protection_enabled', models.BooleanField(default=False)),
                ('default_section_order', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scoring_config', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='section',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='test_catalog.test'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('test', 'section_type', 'order')},
        ),
    ]
