# Generated by Django 5.2.17 on 2026-08-05 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('mcq_single', 'MCQ Single'), ('mcq_multiple', 'MCQ Multiple'), ('true_false_not_given', 'True/False/Not Given'), ('yes_no_not_given', 'Yes/No/Not Given'), ('fill_blank', 'Fill Blank'), ('sentence_completion', 'Sentence Completion'), ('summary_completion', 'Summary Completion'), ('matching_headings', 'Matching Headings'), ('matching_items', 'Matching Items'), ('short_answer', 'Short Answer'), ('writing_prompt', 'Writing Prompt'), ('speaking_prompt', 'Speaking Prompt')], max_length=32)),
                ('prompt', models.TextField()),
                ('instruction', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('options_json', models.JSONField(blank=True, default=list)),
                ('correct_answer_json', models.JSONField(blank=True, default=dict)),
                ('validation_rules_json', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['question_group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CorrectAnswerRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('exact', 'Exact'), ('accepted_variants', 'Accepted Variants'), ('contains', 'Contains'), ('regex', 'Regex'), ('keyword_set', 'Keyword Set'), ('numeric_tolerance', 'Numeric Tolerance'), ('date_variants', 'Date Variants'), ('matching_pairs', 'Matching Pairs'), ('manual_review', 'Manual Review'), ('semantic', 'Semantic')], max_length=32)),
                ('accepted_answers', models.JSONField(blank=True, default=list)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('trim_whitespace', models.BooleanField(default=True)),
                ('ignore_punctuation', models.BooleanField(default=False)),
                ('max_words', models.PositiveIntegerField(blank=True, null=True)),
                ('min_words', models.PositiveIntegerField(blank=True, null=True)),
                ('partial_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('points_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer_rules', to='questions.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('instruction', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('audio_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_groups', to='test_catalog.audioasset')),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_groups', to='test_catalog.passage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='test_catalog.section')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.questiongroup'),
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=1024)),
                ('order', models.PositiveIntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='questions.question')),
            ],
            options={
                'ordering': ['question', 'order'],
                'unique_together': {('question', 'order')},
            },
        ),
    ]
