# Generated by Django 5.2 on 2026-09-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_map_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prompt_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tts/'),
        ),
    ]
