# Generated by Django 5.2.17 on 2026-08-05 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('test_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('practice', 'Practice'), ('exam', 'Exam')], default='exam', max_length=16)),
                ('state', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('evaluating', 'Evaluating'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('server_start_time', models.DateTimeField(blank=True, null=True)),
                ('client_timezone', models.CharField(blank=True, max_length=64)),
                ('locale', models.CharField(blank=True, max_length=16)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('is_auto_submitted', models.BooleanField(default=False)),
                ('is_review_allowed', models.BooleanField(default=False)),
                ('overall_band', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('listening_band', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('reading_band', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('writing_band', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('speaking_band', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('audit_reason', models.TextField(blank=True, null=True)),
                ('current_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_attempts', to='test_catalog.section')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='test_catalog.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('selected_options', models.JSONField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_cleared', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_responses', to='questions.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_responses', to='attempts.attempt')),
            ],
            options={
                'ordering': ['attempt', 'question'],
            },
        ),
        migrations.CreateModel(
            name='AttemptSectionState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('locked', 'Locked')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remaining_seconds', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('band_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('autosave_timestamp', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_states', to='attempts.attempt')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_states', to='test_catalog.section')),
            ],
            options={
                'ordering': ['attempt', 'section'],
            },
        ),
        migrations.CreateModel(
            name='ExamViolationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('violation_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('visibility_hidden', 'Visibility Hidden'), ('fullscreen_exit', 'Fullscreen Exit'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('multiple_tabs', 'Multiple Tabs'), ('network_disconnect', 'Network Disconnect'), ('no_heartbeat', 'No Heartbeat'), ('audio_playback_error', 'Audio Playback Error'), ('manual_review', 'Manual Review')], max_length=32)),
                ('details', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('auto_action_taken', models.CharField(choices=[('none', 'None'), ('warning_shown', 'Warning Shown'), ('attempt_locked', 'Attempt Locked'), ('auto_submitted', 'Auto Submitted')], default='none', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_events', to='attempts.attempt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user'], name='attempts_at_user_id_246094_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['test'], name='attempts_at_test_id_ca9c71_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['state'], name='attempts_at_state_8ebd13_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['expires_at'], name='attempts_at_expires_951120_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answerresponse',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='attemptsectionstate',
            unique_together={('attempt', 'section')},
        ),
    ]
