# Generated by Django 6.0 on 2025-12-19 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('test_number', models.IntegerField()),
                ('test_type', models.CharField(choices=[('academic', 'Academic'), ('general', 'General Training')], default='academic', max_length=20)),
                ('source', models.CharField(choices=[('cambridge_15', 'Cambridge IELTS 15'), ('cambridge_16', 'Cambridge IELTS 16'), ('cambridge_17', 'Cambridge IELTS 17'), ('cambridge_18', 'Cambridge IELTS 18'), ('cambridge_19', 'Cambridge IELTS 19'), ('cambridge_20', 'Cambridge IELTS 20'), ('custom', 'Custom Test')], default='cambridge_16', max_length=20)),
                ('passage_title', models.CharField(max_length=300)),
                ('passage_text', models.TextField(help_text='Full passage text (avoid copyright material)')),
                ('time_limit', models.IntegerField(default=60, help_text='Time limit in minutes')),
                ('total_questions', models.IntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['test_number', 'id'],
                'unique_together': {('test_number', 'source')},
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false_ng', 'True/False/Not Given'), ('matching', 'Matching Headings'), ('completion', 'Sentence Completion'), ('short_answer', 'Short Answer'), ('summary', 'Summary Completion')], max_length=20)),
                ('text', models.TextField(help_text='The question text')),
                ('correct_answer', models.CharField(help_text='Correct answer (for multiple choice, use A,B,C,D)', max_length=500)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer', null=True)),
                ('word_limit', models.IntegerField(default=1, help_text='Maximum words allowed for answer')),
                ('choices', models.TextField(blank=True, help_text="JSON for multiple choice: [{'label':'A','text':'Option A'},...]", null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.readingtest')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('test', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='UserReadingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('band_score', models.FloatField()),
                ('time_taken', models.IntegerField(help_text='Time taken in seconds')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.readingtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.readingquestion')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reading.userreadingattempt')),
            ],
        ),
        migrations.AddIndex(
            model_name='userreadingattempt',
            index=models.Index(fields=['user', 'completed_at'], name='reading_use_user_id_105088_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('attempt', 'question')},
        ),
    ]
