# Generated by Django 5.2.17 on 2026-08-05 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_number', models.IntegerField(choices=[(1, 'Task 1'), (2, 'Task 2')])),
                ('prompt', models.TextField()),
                ('answer_text', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('below_min_word_warning', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('pending_human_review', 'Pending Human Review')], default='pending', max_length=32)),
                ('band_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('criteria_scores', models.JSONField(blank=True, default=dict)),
                ('ai_feedback', models.JSONField(blank=True, default=dict)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('improvement_suggestions', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('prompt_version', models.CharField(blank=True, max_length=255)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('manual_override_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('manual_feedback', models.JSONField(blank=True, default=dict)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to='attempts.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to='questions.question')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
