# Generated by Django 5.2.17 on 2026-08-05 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingAudioSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_number', models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3')])),
                ('prompt', models.TextField()),
                ('storage_key', models.CharField(max_length=512)),
                ('audio_file_url_method', models.CharField(choices=[('signed_url', 'Signed URL'), ('private_media', 'Private Media')], max_length=32)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prep_seconds_allowed', models.PositiveIntegerField(default=0)),
                ('prep_seconds_used', models.PositiveIntegerField(default=0)),
                ('recording_started_at', models.DateTimeField(blank=True, null=True)),
                ('recording_ended_at', models.DateTimeField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('transcription_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('evaluation_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('pending_human_review', 'Pending Human Review')], default='pending', max_length=32)),
                ('band_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('criteria_scores', models.JSONField(blank=True, default=dict)),
                ('ai_feedback', models.JSONField(blank=True, default=dict)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('improvement_suggestions', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('prompt_version', models.CharField(blank=True, max_length=255)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('manual_override_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('manual_feedback', models.JSONField(blank=True, default=dict)),
                ('consent_given', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_submissions', to='attempts.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_submissions', to='questions.question')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
